# Generated by Django 2.2 on 2020-07-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200711_2224'),
        ('playground', '0002_auto_20200712_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='joiner',
            field=models.ManyToManyField(related_name='join_game', to='login.User'),
        ),
    ]
