# Generated by Django 2.2 on 2020-07-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_game_joiner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
