# Generated by Django 2.2 on 2020-07-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_gamemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameManager',
        ),
    ]
