# Generated by Django 2.2 on 2020-07-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_delete_gamemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(max_length=3),
        ),
    ]
